# Definindo o nome do workflow
name: CI/CD Pipeline

# Definindo quando o workflow será executado
on:
  push:
    branches: ['main', 'developer']

# Definindo os jobs que o workflow executará
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login       
        uses: docker/login-action@v3.3.0
        with:
          username: vinicius1183
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.13.0
        with:
          #Context where is the dockerfile, in this case is on root of project.
          context: . 
          tags: 'vinicius1183/fiap-desafio-fase2'
          push: true
